{
 "title": "Fraud Outage",
 "refresh": "15s",
 "panels": [
  {
   "title": "Error Rate (Fraud Spike)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "checkout_error_rate_pct{service=\"checkout-api\"}",
     "legendFormat": "error rate (%)"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "checkout_p99_latency_ms{service=\"checkout-api\"}",
     "legendFormat": "p99 latency (ms)"
    }
   ]
  },
  {
   "title": "Fraud Error Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(checkout_errors_total{service=\"checkout-api\", error_type=\"fraud_svc_unavailable\"}[1m]))",
     "legendFormat": "fraud errors / sec"
    }
   ]
  },
  {
   "title": "Fraud Error Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"checkout-api\"} |= \"fraud-scoring-svc\""
    }
   ]
  }
 ]
}